[package]
name = "intervals-core"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dev-dependencies]
proptest = "1.11"

[[bench]]
name = "assign_lanes"
harness = false

[[bench]]
name = "max_weight_non_overlapping"
harness = false

[[bench]]
name = "max_weight_with_capacity"
harness = false

[[bench]]
name = "covering"
harness = false
