[package]
name = "intervals-core"
version = "0.2.0"
edition = "2024"
license = "MIT"

[dev-dependencies]
proptest = "1.11"

[[bench]]
name = "containment"
harness = false

[[bench]]
name = "assign_lanes"
harness = false

[[bench]]
name = "balance_lanes"
harness = false

[[bench]]
name = "max_weight_non_overlapping"
harness = false

[[bench]]
name = "max_weight_with_capacity"
harness = false

[[bench]]
name = "covering"
harness = false

[[bench]]
name = "minimum_stabbing_points"
harness = false

[[bench]]
name = "max_k_coverage"
harness = false

[[bench]]
name = "max_weight_with_capacity_profile"
harness = false

[[bench]]
name = "nesting_depth"
harness = false

[[bench]]
name = "max_weight_clique"
harness = false

[[bench]]
name = "minimum_cost_dominating_set"
harness = false

[[bench]]
name = "coverage_profile"
harness = false
