[package]
name = "polars-intervals"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
intervals-core = { path = "../intervals-core" }
polars = { version = "0.55.2", default-features = false, features = ["dtype-i8", "dtype-i16", "dtype-u8", "dtype-u16"] }
pyo3-polars = { version = "0.28", default-features = false, features = ["derive"] }
